apiVersion: v1
kind: Service
metadata:
  name: aurora-backend
  labels:
    app: aurora
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: aurora
    tier: backend
  ports:
    - port: 8080
      targetPort: http-server
