apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aurora-frontend
  labels:
    app: aurora
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aurora
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: aurora-frontend
          ports:
            - name: http-server
              containerPort: 8080
            - name: debug
              containerPort: 3000
          env:
            - name: PORT
              value: "8080"
            - name: GUESTBOOK_API_ADDR
              value: aurora-backend:8080
