apiVersion: v1
kind: Service
metadata:
  name: aurora-frontend
  labels:
    app: aurora
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: aurora
    tier: frontend
  ports:
    - port: 80
      targetPort: http-server
