apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aurora-markets
  labels:
    app: aurora
    tier: markets
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aurora
        tier: markets
    spec:
      containers:
        - name: markets
          image: aurora-markets
          env:
            - name: RABBITMQ_ADDR
              value: aurora-rabbitmq:5672
